name: Android Build

on:
  push:
    branches:
      - Demo
  pull_request:
    branches:
      - Demo

jobs:
  build:
    name: Create Release
    runs-on: ubuntu latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from pubspec.yml
        id: get_version
        run: |
          VERSION=$(grep -m1 'version:' "${GITHUB_WORKSPACE}/pubspec.yaml" | awk '{print $2}')
          echo "VERSION: $VERSION"
          version_number="${VERSION%+*}"
          build_number="${VERSION#*+}"
          build_number=$((build_number + 1))
          new_version="$version_number+$build_number"
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
#       - name: Read Release Notes
#         id: read_release_notes
#         run: |
#           echo "::set-output name=RELEASE_NOTES::$(cat ${{ github.workspace }}/release_notes.txt)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: dev_demo/test/${{ env.NEW_VERSION }}
          release_name: Release_v${{ env.NEW_VERSION }}
#           body: |
#             Changes in this Release
#             - ${{ steps.read_release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false

  # flutter_test:
  #   name: Run flutter test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '12.x'
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         # flutter-version: "2.10.5"
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter analyze
  #     - run: flutter test
  build_appbundle:
    name: Build Flutter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: "2.10.5"
          channel: "stable"

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
