name: SALUS_EU_DEV

on:
  push:
    branches:
      - salus_eu/int/integration

jobs:
  build:
    name: Create Release
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from pubspec.yml
        id: get_version
        run: |
          VERSION=$(grep -m1 'version:' "${GITHUB_WORKSPACE}/pubspec.yaml" | awk '{print $2}')
          echo "VERSION: $VERSION"
          version_number="${VERSION%+*}"
          build_number="${VERSION#*+}"
          build_number=$((build_number + 1))
          new_version="$version_number+$build_number"
          echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
      - name: Read Release Notes
        id: read_release_notes
        run: |
          echo "::set-output name=RELEASE_NOTES::$(cat ${{ github.workspace }}/release_notes.txt)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: salus_eu/int/integration${{ env.NEW_VERSION }}
          release_name: Release_v${{ env.NEW_VERSION }}
          body: |
            Changes in this Release
            - ${{ steps.read_release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false
          
  SALUS_EU_DEV_ANDROID:
    name: Salus Dev Android
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Navigate to android folder
        env:
          GROUPS: "5-gen-group, ct-Team"
        run: |
          export GITHUB_USER=runner
          cd android
          source ~/.bashrc
          pwd
          ruby --version
          export APP_NAME=salus_app
          export APP_ID="1:1058715429991:android:00da87821ba3a92b02f8c2"
          export PROJECT_ID=salus-smart-premium
          bundle exec fastlane build_and_release_apk main_file:lib/salus_main.dart
          
  SALUS_EU_DEV_WEB:
    name: Salus Dev WebApp
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Build WebApp 
        run: |
          export GITHUB_USER=runner
          source ~/.bashrc
          pwd
          export APP_NAME=salus_main
          export PROJECT_ID=salus-smart-premium
          export HOSTING_NAME=demoeuprodmain
          flutter build web --web-renderer canvaskit --release -t lib/$APP_NAME.dart
          firebase use $PROJECT_ID
          sed -i '' "s|\"site\": \".*\"|\"site\": \"$HOSTING_NAME\"|" firebase.json
          #Firebase deploy
          firebase deploy --only hosting:$HOSTING_NAME
